name:    essentialsOfCompilation
version: "0.0.1"

dependencies:
- MonadRandom
- base >= 4.7 && < 5
- containers
- exceptions
- logging-effect
- mtl
- prettyprinter
- snail
- text

default-extensions:
- DeriveGeneric
- DerivingStrategies
- ImportQualifiedPost
- LambdaCase
- OverloadedStrings
- RecordWildCards
- TypeApplications

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src

# Runnable executable for our application
executables:
  essentialsOfCompilation:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - essentialsOfCompilation

# Test suite
tests:
  essentialsOfCompilation-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - essentialsOfCompilation
    - hspec
    - HUnit
